=== NatLibFi/yazproxy/etc/yazproxy.xsd
<?xml version="1.0"?>
<!-- XML Schema for YAZ proxy config file.
    $Id: yazproxy.xsd,v 1.2 2004-07-02 12:37:03 adam Exp $
-->
<xs:schema
  xmlns:xs="http://www.w3.org/2001/XMLSchema"
  xmlns:exp="http://explain.z3950.org/dtd/2.0/"
  xmlns="http://indexdata.dk/yazproxy/schema/0.8/"
  targetNamespace="http://indexdata.dk/yazproxy/schema/0.8/"
  >
 <xs:import namespace="http://explain.z3950.org/dtd/2.0/" 
      schemaLocation="zeerex-2.0.xsd"/>
 <xs:element name="proxy">
  <xs:complexType>
   <xs:sequence>
    <xs:element ref="target" minOccurs="0" maxOccurs="unbounded"/>
    <xs:element ref="max-clients" minOccurs="0"/>
    <xs:element ref="log" minOccurs="0"/>
   </xs:sequence>
  </xs:complexType>
 </xs:element>

 <xs:element name="target">
  <xs:complexType>
   <xs:sequence>
     <xs:element ref="url" minOccurs="0" maxOccurs="unbounded"/>
     <xs:element ref="target-timeout" minOccurs="0"/>
     <xs:element ref="client-timeout" minOccurs="0"/>
     <xs:element ref="keepalive" minOccurs="0"/>
     <xs:element ref="limit" minOccurs="0"/>
     <xs:element ref="attribute" minOccurs="0" maxOccurs="unbounded"/>
     <xs:element ref="syntax" minOccurs="0" maxOccurs="unbounded"/>
     <xs:element ref="preinit" minOccurs="0"/>
     <xs:element ref="exp:explain" minOccurs="0"/>
     <xs:element ref="cql2rpn" minOccurs="0"/>
   </xs:sequence>
   <xs:attribute name="default" type="xs:string" use="optional"/>
   <xs:attribute name="name" type="xs:string"/>
  </xs:complexType>
 </xs:element>

 <xs:element name="url" type="xs:string"/>
 <xs:element name="target-timeout" type="xs:integer"/>
 <xs:element name="client-timeout" type="xs:integer"/>
 <xs:element name="bandwidth" type="xs:integer"/>
 <xs:element name="pdu" type="xs:integer"/>
 <xs:element name="retrieve" type="xs:integer"/>
 <xs:element name="preinit" type="xs:integer"/>
 <xs:element name="cql2rpn" type="xs:string"/>

 <xs:element name="keepalive">
  <xs:complexType>
   <xs:sequence>
    <xs:element ref="bandwidth" minOccurs="0"/>
    <xs:element ref="pdu" minOccurs="0"/>
   </xs:sequence>
  </xs:complexType>
 </xs:element>
 <xs:element name="limit">
  <xs:complexType>
   <xs:sequence>
    <xs:element ref="bandwidth" minOccurs="0"/>
    <xs:element ref="pdu" minOccurs="0"/>
    <xs:element ref="retrieve" minOccurs="0"/>
   </xs:sequence>
  </xs:complexType>
 </xs:element>
 
 <xs:element name="attribute">
  <xs:complexType>
   <xs:attribute name="type" type="xs:string"/>
   <xs:attribute name="value" type="xs:string"/>
   <xs:attribute name="error" type="xs:integer"/>
  </xs:complexType>
 </xs:element>

 <xs:element name="syntax">
  <xs:complexType>
   <xs:sequence>
    <xs:element ref="title" minOccurs="0"/>
    <xs:element ref="name" minOccurs="0" maxOccurs="unbounded"/>
   </xs:sequence>
   <xs:attribute name="error" type="xs:string" />
   <xs:attribute name="type" type="xs:string" />
   <xs:attribute name="marcxml" type="xs:string" />
   <xs:attribute name="identifier" type="xs:string" />
   <xs:attribute name="stylesheet" type="xs:string" />
  </xs:complexType>
 </xs:element>

 <xs:element name="title" type="xs:string"/>
 <xs:element name="name" type="xs:string"/>

 <xs:element name="max-clients" type="xs:integer"/>
 <xs:element name="log" type="xs:string"/>

</xs:schema>

=== NatLibFi/yazproxy/etc/config-mafi2ma.xml
<?xml version="1.0"?>
<!-- $Id: config-mafi2ma.xml,v 1.2 2004-12-06 08:00:28 adam Exp $ -->
<proxy xmlns="http://indexdata.dk/yazproxy/schema/0.8/"
 xmlns:xi="http://www.w3.org/2001/XInclude"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://indexdata.dk/yazproxy/schema/0.8/ yazproxy.xsd"
>
<!-- Config can be checked with xerces-c++: PParse -n -s config.xml -->
  <target name="localhost" default="1">
    <url>193.166.7.193:7590</url>
    <target-timeout>30</target-timeout>
    <client-timeout>60</client-timeout>
    <keepalive>
      <bandwidth>1000000</bandwidth>
      <pdu>1000</pdu>
    </keepalive>
    <limit><!-- per minute limits .. -->
      <bandwidth>2000000</bandwidth>
      <pdu>50</pdu>
      <retrieve>100</retrieve>
    </limit>
    <attribute type="1" value="1-11,13-1016"/>
    <attribute type="1" value="*" error="114"/>
    <syntax type="opac"/>
    <syntax type="usmarc" backendtype="none" usemarconstage1="mafi2ma/mafi2ma.ini"/>
    <syntax type="none"/>
    <syntax type="xml" marcxml="1" backendtype="none" usemarconstage1="mafi2ma/mafi2ma.ini"/>
    <syntax type="*" error="238"/>
    <preinit>0</preinit>
    <xi:include href="explain.xml"/>
    <cql2rpn>pqf.properties</cql2rpn>
  </target>
  <target name="*">
    <target-timeout>60</target-timeout>
    <client-timeout>30</client-timeout>
    <!-- everything else -->
  </target>
  <max-clients>50</max-clients>
  <log>client-requests server-requests</log>
</proxy>

=== NatLibFi/yazproxy/etc/config.xml
<?xml version="1.0"?>
<!-- $Id: config.xml,v 1.5 2004-10-18 21:49:21 adam Exp $ -->
<proxy xmlns="http://indexdata.dk/yazproxy/schema/0.8/"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://indexdata.dk/yazproxy/schema/0.8/ yazproxy.xsd"
>
<!-- Config can be checked with xerces-c++: PParse -n -s config.xml -->
  <target name="bagel" default="1">
    <url>indexdata.dk</url>
    <target-timeout>240</target-timeout>
    <client-timeout>180</client-timeout>
    <keepalive>
      <bandwidth>1000000</bandwidth>
      <pdu>1000</pdu>
    </keepalive>
    <limit><!-- per minute limits .. -->
      <bandwidth>2000000</bandwidth>
      <pdu>50</pdu>
      <retrieve>100</retrieve>
    </limit>
    <attribute type="1" value="1-11,13-1016"/>
    <attribute type="1" value="*" error="114"/>
    <syntax type="opac"/>
    <syntax type="usmarc"/>
    <syntax type="none"/>
    <syntax type="xml" marcxml="1"/>
    <syntax type="*" error="238"/>
    <preinit>0</preinit>
    <explain xmlns="http://explain.z3950.org/dtd/2.0/">
       <serverInfo>
       <host>localhost</host>
       <port>9000</port>
       <database>gils</database>
       </serverInfo>
    </explain>
    <cql2rpn>pqf.properties</cql2rpn>
  </target>
  <target name="localhost">
    <url>localhost:9999</url>
    <target-timeout>300</target-timeout>
    <client-timeout>180</client-timeout>
    <keepalive/> <!-- keepalive enabled -->
    <limit><!-- limits .. -->
      <bandwidth>50000</bandwidth>
      <pdu>60</pdu>
      <retrieve>50</retrieve>
    </limit>
    <attribute type="1" value="1-1023"/>
    <attribute type="1" value="*" error="114"/>
    <syntax type="usmarc"/>
    <syntax type="grs1"/>
    <syntax type="xml" marcxml="1" stylesheet="MARC21slim2SRWDC.xsl"
      identifier="info:srw/schema/1/dc-v1.1"
	>
      <name>dc</name>
    </syntax>
    <syntax type="xml" marcxml="1"
      identifier="info:srw/schema/1/marcxml-v1.1"
      >
      <name>marcxml</name>
    </syntax>
    <syntax type="xml" marcxml="1" stylesheet="MARC21slim2MODS.xsl"
      identifier="http://www.loc.gov/mods"
      >
      <name>mods2</name>
    </syntax>
    <syntax type="xml" marcxml="1" stylesheet="MARC21slim2MODS3.xsl"
      identifier="info:srw/schema/1/mods-v3.0"
      >
      <name>mods3</name>
    </syntax>
    <syntax type="none"/>
    <syntax type="*" error="238"/>
    <preinit>2</preinit>
    <explain xmlns="http://explain.z3950.org/dtd/2.0/">
       <serverInfo>
       <host>localhost</host>
       <port>9000</port>
       <database>Default</database>
       </serverInfo>
    </explain>
    <cql2rpn>pqf.properties</cql2rpn>
  </target>
  <target name="*">
    <!-- everything else -->
  </target>
  <max-clients>50</max-clients>
  <log>client-requests server-requests</log>
</proxy>

=== NatLibFi/yazproxy/etc/config-modules.xml
<?xml version="1.0"?>
<!-- 
   Config that uses modules 
-->
<proxy xmlns="http://indexdata.dk/yazproxy/schema/0.9/"
 xmlns:xi="http://www.w3.org/2001/XInclude"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://indexdata.dk/yazproxy/schema/0.9/ yazproxy.xsd"
  >
<!-- Config can be checked with xerces-c++: PParse -n -s config.xml -->
  <target name="localhost" default="1">
    <url>localhost:9999</url>
    <target-timeout>30</target-timeout>
    <client-timeout>60</client-timeout>
    <keepalive>
      <bandwidth>1000000</bandwidth>
      <pdu>1000</pdu>
    </keepalive>
    <limit><!-- per minute limits .. -->
      <bandwidth>2000000</bandwidth>
      <pdu>50</pdu>
      <retrieve>100</retrieve>
    </limit>
    <attribute type="1" value="1-11,13-1016"/>
    <attribute type="1" value="*" error="114"/>
    <syntax type="opac"/>
    <syntax type="usmarc"/>
    <syntax type="none"/>
    <syntax type="xml" marcxml="1"/>
    <syntax type="*" error="238"/>
    <preinit>0</preinit>
    <xi:include href="explain.xml"/>
    <cql2rpn>pqf.properties</cql2rpn>
    <client-authentication module="sample" args="authenticate.pl"/>
  </target>
  <max-clients>50</max-clients>
  <log>client-requests server-requests</log>
  <module>../src/.libs/mod_proxy_sample.so</module>
  <threads>2</threads>
</proxy>
